apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        role-backend: "true"  # Etiketle tam eşleşme yapılır
      containers:
        - name: backend
          image: my-backend-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/testdb
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"



