name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Kodları klonla
        uses: actions/checkout@v3

      - name: Docker image oluştur (frontend)
        run: |
          docker build -t frontend:latest ./frontend

      - name: Docker image oluştur (backend)
        run: |
          docker build -t backend:latest ./backend

      - name: Backend deployment uygula
        run: |
          kubectl apply -f kubernetes/base/backend/deployment.yaml

      - name: Frontend deployment uygula
        run: |
          kubectl apply -f kubernetes/base/frontend/deployment.yaml

